#!/bin/bash

Server_Name=$(uname -n)
IP_Address=$(ifconfig | grep inet | awk 'NR==1{print $2}')
OS_Type=$(uname)
Up_time=$(uptime| awk '{print $3}')


echo "S_no,Server_Name,IP_Adress,OS_ttpe,Uptime" > server_info.csv
echo "1,$Server_Name,$IP_Address,$OS_Type,$Up_time" >> server_info.csv
